export const STORAGE_KEY = "muscle_logs.v6";

export const EFFORT_FRAC = [0.0, 0.25, 0.5, 0.75, 0.9, 1.0];

export const PALETTE = [
  "#FFF8D6",
  "#FFF1B0",
  "#FFE27A",
  "#FFD24A",
  "#A9D86E",
  "#48C774",
  "#34BFA3",
  "#6ECFF6",
  "#FFB3C6",
  "#FF7A8A",
  "#FF4D4F",
  "#A4161A",
];

// `red` is the app's "target/perfect" threshold (level 4 / light blue).
// `overload` is the overstimulation threshold (level 5 / pink-red).
// Values are calibrated to the app's effective-rep stimulus model.
// Source rationale: docs/stimulus-thresholds-sources.md
export const MUSCLE_CFG: Record<string, { red: number; overload: number }> = {
  lower_traps: { red: 13, overload: 19 },
  upper_chest: { red: 13, overload: 18 },
  lower_chest: { red: 15, overload: 21 },
  front_delt_l: { red: 12, overload: 17 },
  front_delt_r: { red: 12, overload: 17 },
  side_delt_l: { red: 12, overload: 17 },
  side_delt_r: { red: 12, overload: 17 },
  traps_front: { red: 13, overload: 18 },
  triceps: { red: 14, overload: 21 },
  biceps_l: { red: 13, overload: 18 },
  biceps_r: { red: 13, overload: 18 },
  forearm_l: { red: 11, overload: 16 },
  forearm_r: { red: 11, overload: 16 },
  abs: { red: 13, overload: 19 },
  obliques_l: { red: 12, overload: 18 },
  obliques_r: { red: 12, overload: 18 },
  quads_l: { red: 17, overload: 24 },
  quads_r: { red: 17, overload: 24 },
  calves_l: { red: 16, overload: 23 },
  calves_r: { red: 16, overload: 23 },
  rear_delt_l: { red: 12, overload: 17 },
  rear_delt_r: { red: 12, overload: 17 },
  traps_back_l: { red: 14, overload: 20 },
  traps_back_r: { red: 14, overload: 20 },
  lower_traps_l: { red: 13, overload: 19 },
  lower_traps_r: { red: 13, overload: 19 },
  lat_l: { red: 14, overload: 20 },
  lat_r: { red: 14, overload: 20 },
  rhomboid_l: { red: 13, overload: 19 },
  rhomboid_r: { red: 13, overload: 19 },
  glutes_l: { red: 17, overload: 24 },
  glutes_r: { red: 17, overload: 24 },
  hamstrings_l: { red: 15, overload: 22 },
  hamstrings_r: { red: 15, overload: 22 },
  lower_back_l: { red: 13, overload: 19 },
  lower_back_r: { red: 13, overload: 19 },
  triceps_l: { red: 14, overload: 21 },
  triceps_r: { red: 14, overload: 21 },
};

export type SetEntry = { reps: number; weight: number; effort: number };
export type LogEntry = {
  id: string;
  ts: number;
  exerciseId: string;
  exercise: string;
  sets: SetEntry[];
  weights: Record<string, number>;
};

export type LogMode = "weighted" | "reps_only";

export type Exercise = {
  id: string;
  name: string;
  weights: Record<string, number>;
  logMode?: LogMode;
  aliases?: string[];
};

export const EXERCISE_DB = [
  { id: "bench-press", name: "Barbell Bench Press", weights: { upper_chest: 0.28, lower_chest: 0.37, front_delt_l: 0.12, front_delt_r: 0.12, triceps: 0.11 } },
  { id: "db-bench-press", name: "Dumbbell Bench Press", weights: { upper_chest: 0.3, lower_chest: 0.38, front_delt_l: 0.1, front_delt_r: 0.1, triceps: 0.12 } },
  { id: "db-flyes", name: "Dumbbell Flyes", aliases: ["Dumbbell Fly", "DB Fly", "DB Flyes", "Dumbell Flyes"], weights: { upper_chest: 0.42, lower_chest: 0.4, front_delt_l: 0.07, front_delt_r: 0.07, triceps: 0.04 } },
  { id: "incline-db-press", name: "Incline DB Press", weights: { upper_chest: 0.5, front_delt_l: 0.2, front_delt_r: 0.2, triceps: 0.1 } },
  { id: "incline-barbell-bench-press", name: "Incline Barbell Bench Press", aliases: ["Incline Barbell Press", "Barbell Incline Bench Press"], weights: { upper_chest: 0.5, lower_chest: 0.1, front_delt_l: 0.15, front_delt_r: 0.15, triceps: 0.1 } },
  { id: "decline-bb-press", name: "Decline Barbell Press", weights: { lower_chest: 0.55, upper_chest: 0.15, triceps: 0.2, front_delt_l: 0.05, front_delt_r: 0.05 } },
  { id: "cable-fly-high", name: "Cable Fly (High->Low)", weights: { lower_chest: 0.55, upper_chest: 0.25, front_delt_l: 0.1, front_delt_r: 0.1 } },
  { id: "cable-fly-low", name: "Cable Fly (Low->High)", weights: { upper_chest: 0.6, front_delt_l: 0.2, front_delt_r: 0.2 } },
  { id: "push-up", name: "Push-Up", weights: { upper_chest: 0.3, lower_chest: 0.35, triceps: 0.2, front_delt_l: 0.075, front_delt_r: 0.075 } },
  { id: "machine-chest-press", name: "Chest Press Machine", weights: { upper_chest: 0.3, lower_chest: 0.4, front_delt_l: 0.1, front_delt_r: 0.1, triceps: 0.1 } },
  { id: "machine-incline-chest-press", name: "Incline Chest Press Machine", weights: { upper_chest: 0.52, lower_chest: 0.08, front_delt_l: 0.18, front_delt_r: 0.18, triceps: 0.04 } },
  { id: "machine-decline-chest-press", name: "Decline Chest Press Machine", weights: { lower_chest: 0.6, upper_chest: 0.15, triceps: 0.15, front_delt_l: 0.05, front_delt_r: 0.05 } },
  { id: "pec-deck", name: "Pec Deck Machine", weights: { upper_chest: 0.45, lower_chest: 0.45, front_delt_l: 0.05, front_delt_r: 0.05 } },
  { id: "smith-bench-press", name: "Smith Machine Bench Press", weights: { upper_chest: 0.3, lower_chest: 0.38, front_delt_l: 0.11, front_delt_r: 0.11, triceps: 0.1 } },
  { id: "smith-incline-bench-press", name: "Smith Machine Incline Bench Press", weights: { upper_chest: 0.54, lower_chest: 0.08, front_delt_l: 0.14, front_delt_r: 0.14, triceps: 0.1 } },
  { id: "assisted-chest-dip", name: "Assisted Chest Dip Machine", weights: { lower_chest: 0.45, upper_chest: 0.15, triceps: 0.25, front_delt_l: 0.075, front_delt_r: 0.075 } },
  { id: "dips", name: "Dips", logMode: "reps_only", weights: { lower_chest: 0.5, upper_chest: 0.15, triceps: 0.25, front_delt_l: 0.05, front_delt_r: 0.05 } },
  { id: "weighted-dips", name: "Weighted Dips", aliases: ["Weighted Dip"], weights: { lower_chest: 0.52, upper_chest: 0.15, triceps: 0.23, front_delt_l: 0.05, front_delt_r: 0.05 } },
  { id: "machine-fly", name: "Machine Fly", weights: { upper_chest: 0.45, lower_chest: 0.45, front_delt_l: 0.05, front_delt_r: 0.05 } },
  { id: "cable-crossover-fly", name: "Cable Crossover Fly", weights: { upper_chest: 0.45, lower_chest: 0.45, front_delt_l: 0.05, front_delt_r: 0.05 } },
  { id: "loop-band-push-up-on-knees", name: "Loop Band Push Up on Knees", logMode: "reps_only", weights: { upper_chest: 0.28, lower_chest: 0.34, triceps: 0.22, front_delt_l: 0.08, front_delt_r: 0.08 } },
  { id: "around-the-worlds", name: "Around the Worlds", weights: { upper_chest: 0.46, lower_chest: 0.42, front_delt_l: 0.06, front_delt_r: 0.06 } },
  { id: "hammerstrength-chest-press", name: "Hammerstrength Chest Press", weights: { upper_chest: 0.32, lower_chest: 0.4, front_delt_l: 0.1, front_delt_r: 0.1, triceps: 0.08 } },
  { id: "dumbbell-squeeze-press", name: "Dumbbell Squeeze Press", weights: { upper_chest: 0.33, lower_chest: 0.45, front_delt_l: 0.04, front_delt_r: 0.04, triceps: 0.14 } },
  { id: "loop-band-standing-incline-chest-press", name: "Loop Band Standing Incline Chest Press", logMode: "reps_only", weights: { upper_chest: 0.46, lower_chest: 0.14, front_delt_l: 0.16, front_delt_r: 0.16, triceps: 0.08 } },
  { id: "smith-machine-decline-press", name: "Smith Machine Decline Press", weights: { lower_chest: 0.58, upper_chest: 0.14, triceps: 0.18, front_delt_l: 0.05, front_delt_r: 0.05 } },
  { id: "push-up-on-knees", name: "Push Up on Knees", logMode: "reps_only", weights: { upper_chest: 0.27, lower_chest: 0.33, triceps: 0.22, front_delt_l: 0.09, front_delt_r: 0.09 } },
  { id: "dumbbell-incline-fly", name: "Dumbbell Incline Fly", weights: { upper_chest: 0.58, lower_chest: 0.28, front_delt_l: 0.07, front_delt_r: 0.07 } },
  { id: "cable-crossover-flat-bench-fly", name: "Cable Crossover Flat Bench Fly", weights: { upper_chest: 0.44, lower_chest: 0.46, front_delt_l: 0.05, front_delt_r: 0.05 } },
  { id: "dumbbell-larson-press", name: "Dumbbell Larson Press", weights: { upper_chest: 0.31, lower_chest: 0.39, front_delt_l: 0.11, front_delt_r: 0.11, triceps: 0.08 } },
  { id: "incline-dumbbell-squeeze-press", name: "Incline Dumbbell Squeeze Press", weights: { upper_chest: 0.54, lower_chest: 0.12, front_delt_l: 0.14, front_delt_r: 0.14, triceps: 0.06 } },
  { id: "dumbbell-pull-over", name: "Dumbbell Pull Over", weights: { upper_chest: 0.22, lower_chest: 0.18, lat_l: 0.2, lat_r: 0.2, triceps: 0.08, traps_back_l: 0.06, traps_back_r: 0.06 } },
  { id: "hammerstrength-decline-chest-press", name: "Hammerstrength Decline Chest Press", weights: { lower_chest: 0.6, upper_chest: 0.15, triceps: 0.15, front_delt_l: 0.05, front_delt_r: 0.05 } },
  { id: "cable-chest-press", name: "Cable Chest Press", weights: { upper_chest: 0.3, lower_chest: 0.42, triceps: 0.14, front_delt_l: 0.07, front_delt_r: 0.07 } },
  { id: "barbell-decline-bench-press", name: "Barbell Decline Bench Press", aliases: ["Decline Barbell Press"], weights: { lower_chest: 0.55, upper_chest: 0.15, triceps: 0.2, front_delt_l: 0.05, front_delt_r: 0.05 } },
  { id: "dumbbell-decline-bench-press", name: "Dumbbell Decline Bench Press", weights: { lower_chest: 0.56, upper_chest: 0.18, triceps: 0.16, front_delt_l: 0.05, front_delt_r: 0.05 } },
  { id: "incline-push-up", name: "Incline Push Up", logMode: "reps_only", weights: { upper_chest: 0.29, lower_chest: 0.34, triceps: 0.2, front_delt_l: 0.085, front_delt_r: 0.085 } },
  { id: "machine-bench-press", name: "Machine Bench Press", weights: { upper_chest: 0.3, lower_chest: 0.4, front_delt_l: 0.1, front_delt_r: 0.1, triceps: 0.1 } },
  { id: "dumbbell-decline-fly", name: "Dumbbell Decline Fly", weights: { lower_chest: 0.58, upper_chest: 0.28, front_delt_l: 0.07, front_delt_r: 0.07 } },
  { id: "decline-push-up", name: "Decline Push Up", logMode: "reps_only", weights: { upper_chest: 0.24, lower_chest: 0.4, triceps: 0.22, front_delt_l: 0.07, front_delt_r: 0.07 } },
  { id: "mid-cable-crossover-fly", name: "Mid Cable Crossover Fly", weights: { upper_chest: 0.43, lower_chest: 0.47, front_delt_l: 0.05, front_delt_r: 0.05 } },
  { id: "ohp", name: "Overhead Press", weights: { front_delt_l: 0.3, front_delt_r: 0.3, side_delt_l: 0.15, side_delt_r: 0.15, traps_front: 0.1 } },
  { id: "seated-dumbbell-press", name: "Seated Dumbbell Press", aliases: ["Dumbbell Shoulder Press", "Seated DB Shoulder Press", "DB Shoulder Press", "Seated Dumbbell Front Press"], weights: { front_delt_l: 0.28, front_delt_r: 0.28, side_delt_l: 0.17, side_delt_r: 0.17, traps_front: 0.05, triceps: 0.05 } },
  { id: "standing-dumbbell-shoulder-press", name: "Standing Dumbbell Shoulder Press", aliases: ["Standing DB Shoulder Press"], weights: { front_delt_l: 0.27, front_delt_r: 0.27, side_delt_l: 0.16, side_delt_r: 0.16, traps_front: 0.08, triceps: 0.06 } },
  { id: "seated-arnold-press", name: "Seated Arnold Press", aliases: ["Arnold Press", "Arnold Dumbbell Press"], weights: { front_delt_l: 0.3, front_delt_r: 0.3, side_delt_l: 0.14, side_delt_r: 0.14, traps_front: 0.05, triceps: 0.07 } },
  { id: "standing-arnold-press", name: "Standing Arnold Press", weights: { front_delt_l: 0.29, front_delt_r: 0.29, side_delt_l: 0.13, side_delt_r: 0.13, traps_front: 0.08, triceps: 0.08 } },
  { id: "seated-barbell-shoulder-press", name: "Seated Barbell Shoulder Press", aliases: ["Barbell Shoulder Press"], weights: { front_delt_l: 0.31, front_delt_r: 0.31, side_delt_l: 0.14, side_delt_r: 0.14, traps_front: 0.04, triceps: 0.06 } },
  { id: "smith-machine-shoulder-press", name: "Smith Machine Shoulder Press", aliases: ["Smith Shoulder Press", "Smith Machine Overhead Shoulder Press"], weights: { front_delt_l: 0.3, front_delt_r: 0.3, side_delt_l: 0.15, side_delt_r: 0.15, traps_front: 0.04, triceps: 0.06 } },
  { id: "machine-shoulder-press", name: "Machine Shoulder Press", aliases: ["Shoulder Press Machine"], weights: { front_delt_l: 0.28, front_delt_r: 0.28, side_delt_l: 0.16, side_delt_r: 0.16, traps_front: 0.04, triceps: 0.08 } },
  { id: "lateral-raise", name: "Dumbbell Lateral Raise", aliases: ["Lateral Raise", "Dumbbell Shoulder Raise"], weights: { side_delt_l: 0.47, side_delt_r: 0.47, traps_front: 0.06 } },
  { id: "seated-lateral-raise", name: "Seated Dumbbell Lateral Raise", weights: { side_delt_l: 0.49, side_delt_r: 0.49, traps_front: 0.02 } },
  { id: "cable-lateral-raise", name: "Cable Lateral Raise (Single Arm)", weights: { side_delt_l: 0.46, side_delt_r: 0.46, traps_front: 0.04, front_delt_l: 0.02, front_delt_r: 0.02 } },
  { id: "lateral-raise-machine", name: "Lateral Raise Machine (Seated)", aliases: ["Machine Lateral Raise"], weights: { side_delt_l: 0.5, side_delt_r: 0.5 } },
  { id: "leaning-lateral-raise", name: "Leaning Dumbbell Lateral Raise", aliases: ["Dumbbell Hanging Lateral Raise"], weights: { side_delt_l: 0.48, side_delt_r: 0.48, traps_front: 0.02, front_delt_l: 0.01, front_delt_r: 0.01 } },
  { id: "behind-back-cable-lateral-raise", name: "Behind-the-Back Cable Lateral Raise", weights: { side_delt_l: 0.47, side_delt_r: 0.47, front_delt_l: 0.03, front_delt_r: 0.03 } },
  { id: "upright-row", name: "Standing Barbell Upright Row", weights: { side_delt_l: 0.3, side_delt_r: 0.3, traps_front: 0.25, front_delt_l: 0.075, front_delt_r: 0.075 } },
  { id: "front-raise", name: "Front Raise", aliases: ["Dumbbell Front Raise", "Barbell Front Raise"], weights: { front_delt_l: 0.48, front_delt_r: 0.48, traps_front: 0.04 } },
  { id: "push-press", name: "Barbell Push Press", aliases: ["Push Press"], weights: { front_delt_l: 0.25, front_delt_r: 0.25, side_delt_l: 0.14, side_delt_r: 0.14, traps_front: 0.12, triceps: 0.1 } },
  { id: "seated-military-press", name: "Seated Military Press", weights: { front_delt_l: 0.31, front_delt_r: 0.31, side_delt_l: 0.13, side_delt_r: 0.13, traps_front: 0.04, triceps: 0.08 } },
  { id: "standing-military-press", name: "Standing Military Press", weights: { front_delt_l: 0.29, front_delt_r: 0.29, side_delt_l: 0.14, side_delt_r: 0.14, traps_front: 0.06, triceps: 0.08 } },
  { id: "dumbbell-z-press", name: "Dumbbell Z Press", aliases: ["Z Press"], weights: { front_delt_l: 0.29, front_delt_r: 0.29, side_delt_l: 0.16, side_delt_r: 0.16, traps_front: 0.03, triceps: 0.07 } },
  { id: "landmine-press", name: "Landmine Press", weights: { front_delt_l: 0.23, front_delt_r: 0.23, side_delt_l: 0.1, side_delt_r: 0.1, upper_chest: 0.14, traps_front: 0.08, triceps: 0.1, forearm_l: 0.01, forearm_r: 0.01 } },
  { id: "single-arm-landmine-press", name: "Single Arm Landmine Press", weights: { front_delt_l: 0.24, front_delt_r: 0.24, side_delt_l: 0.11, side_delt_r: 0.11, upper_chest: 0.12, traps_front: 0.07, triceps: 0.08, obliques_l: 0.015, obliques_r: 0.015 } },
  { id: "half-kneeling-landmine-press", name: "Half Kneeling Landmine Press", weights: { front_delt_l: 0.23, front_delt_r: 0.23, side_delt_l: 0.1, side_delt_r: 0.1, upper_chest: 0.1, traps_front: 0.06, triceps: 0.08, abs: 0.05, obliques_l: 0.025, obliques_r: 0.025 } },
  { id: "kettlebell-overhead-press", name: "Kettlebell Overhead Press", aliases: ["KB Overhead Press"], weights: { front_delt_l: 0.28, front_delt_r: 0.28, side_delt_l: 0.14, side_delt_r: 0.14, traps_front: 0.05, triceps: 0.08, forearm_l: 0.015, forearm_r: 0.015 } },
  { id: "kettlebell-turkish-get-up", name: "Kettlebell Turkish Get Up", weights: { front_delt_l: 0.11, front_delt_r: 0.11, side_delt_l: 0.07, side_delt_r: 0.07, traps_front: 0.08, triceps: 0.08, forearm_l: 0.03, forearm_r: 0.03, abs: 0.1, obliques_l: 0.06, obliques_r: 0.06, glutes_l: 0.04, glutes_r: 0.04, quads_l: 0.04, quads_r: 0.04, lower_back_l: 0.03, lower_back_r: 0.03 } },
  { id: "kettlebell-upright-row", name: "Kettlebell Upright Row", weights: { side_delt_l: 0.17, side_delt_r: 0.17, traps_front: 0.28, front_delt_l: 0.08, front_delt_r: 0.08, forearm_l: 0.06, forearm_r: 0.06, biceps_l: 0.05, biceps_r: 0.05 } },
  { id: "single-arm-kettlebell-overhead-press", name: "Single Arm Kettlebell Overhead Press", aliases: ["Single Arm KB Press"], weights: { front_delt_l: 0.27, front_delt_r: 0.27, side_delt_l: 0.13, side_delt_r: 0.13, traps_front: 0.06, triceps: 0.07, forearm_l: 0.015, forearm_r: 0.015, obliques_l: 0.02, obliques_r: 0.02 } },
  { id: "machine-iso-lateral-shoulder-press", name: "Machine Iso-Lateral Shoulder Press", aliases: ["Iso Lateral Shoulder Press", "Hammerstrength Shoulder Press"], weights: { front_delt_l: 0.29, front_delt_r: 0.29, side_delt_l: 0.15, side_delt_r: 0.15, traps_front: 0.03, triceps: 0.09 } },
  { id: "cable-shoulder-press", name: "Cable Shoulder Press", weights: { front_delt_l: 0.27, front_delt_r: 0.27, side_delt_l: 0.16, side_delt_r: 0.16, traps_front: 0.04, triceps: 0.1 } },
  { id: "single-arm-cable-shoulder-press", name: "Single Arm Cable Shoulder Press", weights: { front_delt_l: 0.26, front_delt_r: 0.26, side_delt_l: 0.15, side_delt_r: 0.15, traps_front: 0.04, triceps: 0.09, abs: 0.02, obliques_l: 0.015, obliques_r: 0.015 } },
  { id: "cable-shoulder-internal-rotation", name: "Cable Shoulder Internal Rotation", weights: { front_delt_l: 0.18, front_delt_r: 0.18, upper_chest: 0.2, lower_chest: 0.1, lat_l: 0.08, lat_r: 0.08, forearm_l: 0.04, forearm_r: 0.04, traps_front: 0.04, triceps: 0.06 } },
  { id: "pike-push-up", name: "Pike Push Up", logMode: "reps_only", weights: { front_delt_l: 0.24, front_delt_r: 0.24, side_delt_l: 0.11, side_delt_r: 0.11, upper_chest: 0.08, triceps: 0.14, traps_front: 0.04, forearm_l: 0.02, forearm_r: 0.02 } },
  { id: "handstand-push-up", name: "Handstand Push Up", logMode: "reps_only", weights: { front_delt_l: 0.26, front_delt_r: 0.26, side_delt_l: 0.12, side_delt_r: 0.12, traps_front: 0.08, triceps: 0.12, forearm_l: 0.02, forearm_r: 0.02 } },
  { id: "plate-front-raise", name: "Plate Front Raise", aliases: ["Front Plate Raise"], weights: { front_delt_l: 0.46, front_delt_r: 0.46, traps_front: 0.06, forearm_l: 0.01, forearm_r: 0.01 } },
  { id: "cable-front-raise", name: "Cable Front Raise", weights: { front_delt_l: 0.45, front_delt_r: 0.45, traps_front: 0.06, forearm_l: 0.02, forearm_r: 0.02 } },
  { id: "loop-band-underhand-front-raise", name: "Loop Band Underhand Front Raise", logMode: "reps_only", weights: { front_delt_l: 0.45, front_delt_r: 0.45, traps_front: 0.04, forearm_l: 0.03, forearm_r: 0.03 } },
  { id: "battle-ropes", name: "Battle Ropes", logMode: "reps_only", weights: { front_delt_l: 0.14, front_delt_r: 0.14, side_delt_l: 0.07, side_delt_r: 0.07, traps_front: 0.12, triceps: 0.08, forearm_l: 0.07, forearm_r: 0.07, abs: 0.08, obliques_l: 0.06, obliques_r: 0.06, calves_l: 0.02, calves_r: 0.02 } },
  { id: "ez-bar-upright-row", name: "EZ Bar Upright Row", weights: { side_delt_l: 0.28, side_delt_r: 0.28, traps_front: 0.25, front_delt_l: 0.06, front_delt_r: 0.06, forearm_l: 0.035, forearm_r: 0.035 } },
  { id: "cable-upright-row", name: "Cable Upright Row", weights: { side_delt_l: 0.29, side_delt_r: 0.29, traps_front: 0.24, front_delt_l: 0.06, front_delt_r: 0.06, forearm_l: 0.03, forearm_r: 0.03 } },
  { id: "wide-grip-upright-row", name: "Wide Grip Upright Row", weights: { side_delt_l: 0.33, side_delt_r: 0.33, traps_front: 0.2, front_delt_l: 0.05, front_delt_r: 0.05, forearm_l: 0.02, forearm_r: 0.02 } },
  { id: "rear-delt-row", name: "Rear Delt Row", aliases: ["Rear Delt Cable Row"], weights: { rear_delt_l: 0.31, rear_delt_r: 0.31, traps_back_l: 0.14, traps_back_r: 0.14, rhomboid_l: 0.03, rhomboid_r: 0.03, forearm_l: 0.02, forearm_r: 0.02 } },
  { id: "bb-curl", name: "Barbell Curl", weights: { biceps_l: 0.4, biceps_r: 0.4, forearm_l: 0.1, forearm_r: 0.1 } },
  { id: "ez-bar-curl", name: "EZ Bar Curl", weights: { biceps_l: 0.38, biceps_r: 0.38, forearm_l: 0.12, forearm_r: 0.12 } },
  { id: "seated-bb-curl", name: "Seated Barbell Curl", weights: { biceps_l: 0.43, biceps_r: 0.43, forearm_l: 0.07, forearm_r: 0.07 } },
  { id: "db-curl", name: "Dumbbell Bicep Curl", weights: { biceps_l: 0.41, biceps_r: 0.41, forearm_l: 0.09, forearm_r: 0.09 } },
  { id: "alt-db-curl", name: "Alternating Dumbbell Curl", weights: { biceps_l: 0.39, biceps_r: 0.39, forearm_l: 0.11, forearm_r: 0.11 } },
  { id: "seated-db-curl", name: "Seated Dumbbell Curl", aliases: ["Seated Bicep Curl"], weights: { biceps_l: 0.43, biceps_r: 0.43, forearm_l: 0.07, forearm_r: 0.07 } },
  { id: "incline-db-curl", name: "Incline Dumbbell Curl", weights: { biceps_l: 0.44, biceps_r: 0.44, forearm_l: 0.06, forearm_r: 0.06 } },
  { id: "db-hammer-curl", name: "Hammer Curl", aliases: ["DB Hammer Curl"], weights: { biceps_l: 0.28, biceps_r: 0.28, forearm_l: 0.22, forearm_r: 0.22 } },
  { id: "concentration-curl", name: "Concentration Curl", weights: { biceps_l: 0.46, biceps_r: 0.46, forearm_l: 0.04, forearm_r: 0.04 } },
  { id: "preacher-bb-curl", name: "Preacher Curl (Barbell)", aliases: ["Preacher Curl"], weights: { biceps_l: 0.45, biceps_r: 0.45, forearm_l: 0.05, forearm_r: 0.05 } },
  { id: "spider-curl", name: "Spider Curl", weights: { biceps_l: 0.44, biceps_r: 0.44, forearm_l: 0.06, forearm_r: 0.06 } },
  { id: "cable-bicep-curl", name: "Cable Bicep Curl", weights: { biceps_l: 0.43, biceps_r: 0.43, forearm_l: 0.07, forearm_r: 0.07 } },
  { id: "cable-curl", name: "Standing Cable Curl", aliases: ["Cable Curl"], weights: { biceps_l: 0.42, biceps_r: 0.42, forearm_l: 0.08, forearm_r: 0.08 } },
  { id: "single-arm-cable-curl", name: "Single Arm Cable Curl", weights: { biceps_l: 0.41, biceps_r: 0.41, forearm_l: 0.09, forearm_r: 0.09 } },
  { id: "rope-cable-curl", name: "Rope Cable Curl", weights: { biceps_l: 0.34, biceps_r: 0.34, forearm_l: 0.16, forearm_r: 0.16 } },
  { id: "overhead-cable-curl", name: "Overhead Cable Curl", weights: { biceps_l: 0.37, biceps_r: 0.37, front_delt_l: 0.08, front_delt_r: 0.08, forearm_l: 0.05, forearm_r: 0.05 } },
  { id: "seated-cable-curl", name: "Seated Cable Curl", weights: { biceps_l: 0.44, biceps_r: 0.44, forearm_l: 0.06, forearm_r: 0.06 } },
  { id: "machine-bicep-curl", name: "Machine Bicep Curl", weights: { biceps_l: 0.45, biceps_r: 0.45, forearm_l: 0.05, forearm_r: 0.05 } },
  { id: "preacher-curl-machine", name: "Preacher Curl Machine", weights: { biceps_l: 0.46, biceps_r: 0.46, forearm_l: 0.04, forearm_r: 0.04 } },
  { id: "seated-supported-machine-curl", name: "Seated Supported Machine Curl", weights: { biceps_l: 0.43, biceps_r: 0.43, forearm_l: 0.07, forearm_r: 0.07 } },
  { id: "reverse-grip-cable-curl", name: "Reverse Grip Cable Curl", weights: { biceps_l: 0.3, biceps_r: 0.3, forearm_l: 0.2, forearm_r: 0.2 } },
  { id: "db-hammer-preacher-curl", name: "Dumbbell Hammer Preacher Curl", weights: { biceps_l: 0.34, biceps_r: 0.34, forearm_l: 0.16, forearm_r: 0.16 } },
  { id: "half-kneeling-preacher-curl", name: "Half Kneeling Preacher Curl", weights: { biceps_l: 0.45, biceps_r: 0.45, forearm_l: 0.05, forearm_r: 0.05 } },
  { id: "zottman-curl", name: "Zottman Curl", weights: { biceps_l: 0.34, biceps_r: 0.34, forearm_l: 0.16, forearm_r: 0.16 } },
  { id: "db-hammer-curl-to-shoulder-press", name: "Dumbbell Hammer Curl to Shoulder Press", weights: { biceps_l: 0.18, biceps_r: 0.18, forearm_l: 0.09, forearm_r: 0.09, front_delt_l: 0.14, front_delt_r: 0.14, side_delt_l: 0.07, side_delt_r: 0.07, triceps: 0.04 } },
  { id: "cross-body-hammer-curl", name: "Cross Body Hammer Curl", aliases: ["Dumbbell Cross Body Hammer Curl"], weights: { biceps_l: 0.31, biceps_r: 0.31, forearm_l: 0.19, forearm_r: 0.19 } },
  { id: "reverse-grip-barbell-curl", name: "Reverse Grip Barbell Curl", aliases: ["Reverse Curl"], weights: { biceps_l: 0.3, biceps_r: 0.3, forearm_l: 0.2, forearm_r: 0.2 } },
  { id: "palms-down-dumbbell-wrist-curl", name: "Palms-Down Dumbbell Wrist Curl", weights: { forearm_l: 0.5, forearm_r: 0.5 } },
  { id: "palms-down-barbell-wrist-curl", name: "Palms-Down Barbell Wrist Curl", weights: { forearm_l: 0.5, forearm_r: 0.5 } },
  { id: "farmers-walk", name: "Farmer's Walk", weights: { forearm_l: 0.26, forearm_r: 0.26, traps_front: 0.12, lower_back_l: 0.04, lower_back_r: 0.04, abs: 0.08, obliques_l: 0.06, obliques_r: 0.06, calves_l: 0.03, calves_r: 0.03, glutes_l: 0.01, glutes_r: 0.01 } },
  { id: "cable-wrist-curl", name: "Cable Wrist Curl", weights: { forearm_l: 0.5, forearm_r: 0.5 } },
  { id: "plate-pinch", name: "Plate Pinch", weights: { forearm_l: 0.5, forearm_r: 0.5 } },
  { id: "handle-band-reverse-curl", name: "Handle Band Reverse Curl", logMode: "reps_only", weights: { biceps_l: 0.26, biceps_r: 0.26, forearm_l: 0.24, forearm_r: 0.24 } },
  { id: "db-hammer-curl-with-twist", name: "Dumbbell Hammer Curl with Twist", weights: { biceps_l: 0.34, biceps_r: 0.34, forearm_l: 0.16, forearm_r: 0.16 } },
  { id: "db-curl-to-shoulder-press", name: "Dumbbell Curl to Shoulder Press", weights: { biceps_l: 0.2, biceps_r: 0.2, forearm_l: 0.04, forearm_r: 0.04, front_delt_l: 0.14, front_delt_r: 0.14, side_delt_l: 0.08, side_delt_r: 0.08, triceps: 0.08 } },
  { id: "db-reverse-curl", name: "Dumbbell Reverse Curl", weights: { biceps_l: 0.29, biceps_r: 0.29, forearm_l: 0.21, forearm_r: 0.21 } },
  { id: "db-preacher-curl", name: "Dumbbell Preacher Curl", weights: { biceps_l: 0.46, biceps_r: 0.46, forearm_l: 0.04, forearm_r: 0.04 } },
  { id: "incline-db-hammer-curl", name: "Incline Dumbbell Hammer Curl", aliases: ["Dumbbell Hammer Curl on Incline Bench"], weights: { biceps_l: 0.31, biceps_r: 0.31, forearm_l: 0.19, forearm_r: 0.19 } },
  { id: "seated-incline-db-curl", name: "Seated Incline Dumbbell Curl", weights: { biceps_l: 0.45, biceps_r: 0.45, forearm_l: 0.05, forearm_r: 0.05 } },
  { id: "incline-inner-bicep-curl", name: "Incline Inner Bicep Curl", weights: { biceps_l: 0.46, biceps_r: 0.46, forearm_l: 0.04, forearm_r: 0.04 } },
  { id: "alternating-incline-db-curl", name: "Alternating Incline Dumbbell Curl", weights: { biceps_l: 0.43, biceps_r: 0.43, forearm_l: 0.07, forearm_r: 0.07 } },
  { id: "seated-alternating-incline-db-curl", name: "Seated Alternating Incline Dumbbell Curl", weights: { biceps_l: 0.43, biceps_r: 0.43, forearm_l: 0.07, forearm_r: 0.07 } },
  { id: "standing-inner-bicep-curl", name: "Standing Inner Bicep Curl", weights: { biceps_l: 0.45, biceps_r: 0.45, forearm_l: 0.05, forearm_r: 0.05 } },
  { id: "db-curl-and-rotation", name: "Dumbbell Curl and Rotation", weights: { biceps_l: 0.4, biceps_r: 0.4, forearm_l: 0.1, forearm_r: 0.1 } },
  { id: "bayes-curl", name: "Bayes Curl", aliases: ["Bayesian Curl"], weights: { biceps_l: 0.45, biceps_r: 0.45, forearm_l: 0.05, forearm_r: 0.05 } },
  { id: "drag-curl", name: "Drag Curl", weights: { biceps_l: 0.45, biceps_r: 0.45, forearm_l: 0.05, forearm_r: 0.05 } },
  { id: "db-prone-incline-curl", name: "Dumbbell Prone Incline Curl", weights: { biceps_l: 0.46, biceps_r: 0.46, forearm_l: 0.04, forearm_r: 0.04 } },
  { id: "high-cable-curl", name: "High Cable Curl", weights: { biceps_l: 0.37, biceps_r: 0.37, front_delt_l: 0.08, front_delt_r: 0.08, forearm_l: 0.05, forearm_r: 0.05 } },
  { id: "db-hammer-drag-curl", name: "Dumbbell Hammer Drag Curl", weights: { biceps_l: 0.32, biceps_r: 0.32, forearm_l: 0.18, forearm_r: 0.18 } },
  { id: "single-arm-machine-bicep-curl", name: "Single Arm Machine Bicep Curl", weights: { biceps_l: 0.45, biceps_r: 0.45, forearm_l: 0.05, forearm_r: 0.05 } },
  { id: "reverse-grip-ez-bar-curl", name: "Reverse Grip EZ Bar Curl", weights: { biceps_l: 0.31, biceps_r: 0.31, forearm_l: 0.19, forearm_r: 0.19 } },
  { id: "reverse-grip-cable-preacher-curl", name: "Reverse Grip Cable Preacher Curl", weights: { biceps_l: 0.33, biceps_r: 0.33, forearm_l: 0.17, forearm_r: 0.17 } },
  { id: "ez-bar-preacher-curl", name: "EZ Bar Preacher Curl", weights: { biceps_l: 0.44, biceps_r: 0.44, forearm_l: 0.06, forearm_r: 0.06 } },
  { id: "close-grip-ez-bar-curl", name: "Close Grip EZ Bar Curl", weights: { biceps_l: 0.4, biceps_r: 0.4, forearm_l: 0.1, forearm_r: 0.1 } },
  { id: "close-grip-bench-press", name: "Close Grip Bench Press", weights: { triceps: 0.4, upper_chest: 0.25, lower_chest: 0.15, front_delt_l: 0.1, front_delt_r: 0.1 } },
  { id: "smith-close-grip-bench", name: "Smith Machine Close Grip Bench Press", weights: { triceps: 0.45, upper_chest: 0.22, lower_chest: 0.13, front_delt_l: 0.1, front_delt_r: 0.1 } },
  { id: "smith-jm-press", name: "Smith Machine JM Press", weights: { triceps: 0.55, upper_chest: 0.15, front_delt_l: 0.1, front_delt_r: 0.1, lower_chest: 0.05, forearm_l: 0.025, forearm_r: 0.025 } },
  { id: "bb-skull-crusher", name: "Barbell Skull Crusher (Lying Triceps Extension)", weights: { triceps: 0.75, front_delt_l: 0.08, front_delt_r: 0.08, forearm_l: 0.045, forearm_r: 0.045 } },
  { id: "ez-skull-crusher", name: "EZ Bar Skull Crusher", weights: { triceps: 0.78, front_delt_l: 0.07, front_delt_r: 0.07, forearm_l: 0.04, forearm_r: 0.04 } },
  { id: "db-skull-crusher", name: "Dumbbell Skull Crusher", weights: { triceps: 0.76, front_delt_l: 0.08, front_delt_r: 0.08, forearm_l: 0.04, forearm_r: 0.04 } },
  { id: "incline-db-triceps-extension", name: "Incline Dumbbell Triceps Extension", weights: { triceps: 0.78, front_delt_l: 0.07, front_delt_r: 0.07, forearm_l: 0.04, forearm_r: 0.04 } },
  { id: "overhead-triceps", name: "Seated Overhead Dumbbell Extension", aliases: ["Overhead Triceps Ext."], weights: { triceps: 0.85, front_delt_l: 0.075, front_delt_r: 0.075 } },
  { id: "single-arm-overhead-db-extension", name: "Single Arm Overhead Dumbbell Extension", weights: { triceps: 0.82, front_delt_l: 0.045, front_delt_r: 0.045, forearm_l: 0.045, forearm_r: 0.045 } },
  { id: "triceps-pushdown", name: "Cable Triceps Pushdown (Straight Bar)", aliases: ["Triceps Pushdown"], weights: { triceps: 0.9, front_delt_l: 0.05, front_delt_r: 0.05 } },
  { id: "rope-triceps-pushdown", name: "Rope Triceps Pushdown", weights: { triceps: 0.82, front_delt_l: 0.06, front_delt_r: 0.06, forearm_l: 0.03, forearm_r: 0.03 } },
  { id: "reverse-grip-cable-pushdown", name: "Reverse Grip Cable Pushdown", weights: { triceps: 0.78, forearm_l: 0.11, forearm_r: 0.11 } },
  { id: "single-arm-cable-pushdown", name: "Single Arm Cable Pushdown", weights: { triceps: 0.83, front_delt_l: 0.035, front_delt_r: 0.035, forearm_l: 0.05, forearm_r: 0.05 } },
  { id: "overhead-cable-triceps-extension", name: "Overhead Cable Triceps Extension (Rope or Bar)", weights: { triceps: 0.8, front_delt_l: 0.08, front_delt_r: 0.08, forearm_l: 0.02, forearm_r: 0.02 } },
  { id: "db-kickback", name: "Dumbbell Kickback", weights: { triceps: 0.35, rear_delt_l: 0.15, rear_delt_r: 0.15, traps_back_l: 0.1, traps_back_r: 0.1, forearm_l: 0.075, forearm_r: 0.075 } },
  { id: "cable-kickback", name: "Cable Kickback", weights: { triceps: 0.52, rear_delt_l: 0.12, rear_delt_r: 0.12, traps_back_l: 0.08, traps_back_r: 0.08, forearm_l: 0.04, forearm_r: 0.04 } },
  { id: "cross-body-cable-extension", name: "Cross-Body Cable Extension", weights: { triceps: 0.7, front_delt_l: 0.06, front_delt_r: 0.06, forearm_l: 0.09, forearm_r: 0.09 } },
  { id: "triceps-extension-machine", name: "Triceps Extension Machine (Seated)", weights: { triceps: 0.85, front_delt_l: 0.05, front_delt_r: 0.05, forearm_l: 0.025, forearm_r: 0.025 } },
  { id: "dip-machine-triceps", name: "Dip Machine (Chest/Triceps Focus)", weights: { triceps: 0.45, lower_chest: 0.25, upper_chest: 0.1, front_delt_l: 0.1, front_delt_r: 0.1 } },
  { id: "assisted-triceps-dip-machine", name: "Assisted Triceps Dip Machine", weights: { triceps: 0.42, lower_chest: 0.25, upper_chest: 0.08, front_delt_l: 0.11, front_delt_r: 0.11, traps_front: 0.03 } },
  { id: "crunch", name: "Crunch", logMode: "reps_only", weights: { abs: 0.85, obliques_l: 0.075, obliques_r: 0.075 } },
  { id: "sit-up", name: "Sit-Up", logMode: "reps_only", weights: { abs: 0.78, obliques_l: 0.11, obliques_r: 0.11 } },
  { id: "weighted-sit-up", name: "Weighted Sit-Up", weights: { abs: 0.78, obliques_l: 0.11, obliques_r: 0.11 } },
  { id: "leg-raise-lying", name: "Leg Raise (Lying)", logMode: "reps_only", weights: { abs: 0.78, obliques_l: 0.11, obliques_r: 0.11 } },
  { id: "leg-raise", name: "Hanging Leg Raise", logMode: "reps_only", weights: { abs: 0.75, obliques_l: 0.1, obliques_r: 0.1 } },
  { id: "hanging-knee-raise", name: "Hanging Knee Raise", logMode: "reps_only", weights: { abs: 0.7, obliques_l: 0.15, obliques_r: 0.15 } },
  { id: "plank", name: "Plank", logMode: "reps_only", weights: { abs: 0.5, obliques_l: 0.25, obliques_r: 0.25 } },
  { id: "side-plank", name: "Side Plank", logMode: "reps_only", weights: { abs: 0.2, obliques_l: 0.4, obliques_r: 0.4 } },
  { id: "cable-crunch", name: "Cable Crunch (Kneeling)", aliases: ["Cable Crunch"], weights: { abs: 0.75, obliques_l: 0.125, obliques_r: 0.125 } },
  { id: "standing-cable-crunch", name: "Standing Cable Crunch", weights: { abs: 0.7, obliques_l: 0.15, obliques_r: 0.15 } },
  { id: "seated-ab-crunch-machine", name: "Seated Ab Crunch Machine", weights: { abs: 0.82, obliques_l: 0.09, obliques_r: 0.09 } },
  { id: "cable-woodchopper-high", name: "Cable Woodchopper (High to Low)", weights: { abs: 0.1, obliques_l: 0.45, obliques_r: 0.45 } },
  { id: "cable-woodchopper-low", name: "Cable Woodchopper (Low to High)", weights: { abs: 0.1, obliques_l: 0.45, obliques_r: 0.45 } },
  { id: "russian-twist", name: "Russian Twist", logMode: "reps_only", weights: { abs: 0.2, obliques_l: 0.4, obliques_r: 0.4 } },
  { id: "ab-roller", name: "Ab Roller", logMode: "reps_only", weights: { abs: 0.7, obliques_l: 0.15, obliques_r: 0.15 } },
  { id: "squat", name: "Barbell Back Squat", aliases: ["Back Squat"], weights: { quads_l: 0.4, quads_r: 0.4, calves_l: 0.1, calves_r: 0.1 } },
  { id: "front-squat", name: "Front Squat", weights: { quads_l: 0.44, quads_r: 0.44, glutes_l: 0.06, glutes_r: 0.06 } },
  { id: "hack-squat-machine", name: "Hack Squat Machine", weights: { quads_l: 0.38, quads_r: 0.38, glutes_l: 0.08, glutes_r: 0.08, calves_l: 0.04, calves_r: 0.04 } },
  { id: "smith-squat", name: "Smith Machine Squat", weights: { quads_l: 0.32, quads_r: 0.32, glutes_l: 0.14, glutes_r: 0.14, calves_l: 0.03, calves_r: 0.03, lower_back_l: 0.01, lower_back_r: 0.01 } },
  { id: "belt-squat", name: "Belt Squat", weights: { quads_l: 0.34, quads_r: 0.34, glutes_l: 0.12, glutes_r: 0.12, hamstrings_l: 0.03, hamstrings_r: 0.03, calves_l: 0.02, calves_r: 0.02 } },
  { id: "goblet-squat", name: "Goblet Squat", weights: { quads_l: 0.38, quads_r: 0.38, glutes_l: 0.1, glutes_r: 0.1, calves_l: 0.02, calves_r: 0.02 } },
  { id: "bodyweight-squat", name: "Bodyweight Squat", weights: { quads_l: 0.36, quads_r: 0.36, glutes_l: 0.11, glutes_r: 0.11, calves_l: 0.02, calves_r: 0.02, hamstrings_l: 0.01, hamstrings_r: 0.01 } },
  { id: "bulgarian-split-squat", name: "Bulgarian Split Squat", weights: { quads_l: 0.3, quads_r: 0.3, glutes_l: 0.15, glutes_r: 0.15, hamstrings_l: 0.05, hamstrings_r: 0.05 } },
  { id: "db-lunge", name: "Dumbbell Lunge", weights: { quads_l: 0.3, quads_r: 0.3, glutes_l: 0.12, glutes_r: 0.12, hamstrings_l: 0.08, hamstrings_r: 0.08 } },
  { id: "walking-lunge", name: "Walking Lunge", weights: { quads_l: 0.28, quads_r: 0.28, glutes_l: 0.14, glutes_r: 0.14, hamstrings_l: 0.08, hamstrings_r: 0.08 } },
  { id: "step-up", name: "Step Up", weights: { quads_l: 0.32, quads_r: 0.32, glutes_l: 0.12, glutes_r: 0.12, hamstrings_l: 0.04, hamstrings_r: 0.04, calves_l: 0.02, calves_r: 0.02 } },
  { id: "leg-press", name: "Leg Press Machine", aliases: ["Leg Press"], weights: { quads_l: 0.45, quads_r: 0.45, calves_l: 0.05, calves_r: 0.05 } },
  { id: "leg-press-calf-raise", name: "Leg Press Calf Raise", aliases: ["Calf Press"], weights: { calves_l: 0.43, calves_r: 0.43, hamstrings_l: 0.05, hamstrings_r: 0.05, glutes_l: 0.02, glutes_r: 0.02 } },
  { id: "leg-extension", name: "Leg Extension Machine", aliases: ["Leg Extension"], weights: { quads_l: 0.5, quads_r: 0.5 } },
  { id: "calf-raise", name: "Standing Calf Raise Machine", aliases: ["Calf Raise", "Standing Machine Calf Raise"], weights: { calves_l: 0.5, calves_r: 0.5 } },
  { id: "seated-calf-raise", name: "Seated Calf Raise Machine", aliases: ["Seated Calf Raise", "Seated Machine Calf Press"], weights: { calves_l: 0.5, calves_r: 0.5 } },
  { id: "standing-dumbbell-calf-raise", name: "Standing Dumbbell Calf Raise", weights: { calves_l: 0.5, calves_r: 0.5 } },
  { id: "seated-dumbbell-calf-raise", name: "Seated Dumbbell Calf Raise", weights: { calves_l: 0.5, calves_r: 0.5 } },
  { id: "standing-barbell-calf-raise", name: "Standing Barbell Calf Raise", weights: { calves_l: 0.5, calves_r: 0.5 } },
  { id: "smith-machine-calf-raise", name: "Smith Machine Calf Raise", weights: { calves_l: 0.5, calves_r: 0.5 } },
  { id: "pull-up", name: "Pull-Up", logMode: "reps_only", weights: { lat_l: 0.35, lat_r: 0.35, traps_back_l: 0.07, traps_back_r: 0.07, lower_traps_l: 0.02, lower_traps_r: 0.02, rhomboid_l: 0.01, rhomboid_r: 0.01, biceps_l: 0.05, biceps_r: 0.05, forearm_l: 0.025, forearm_r: 0.025 } },
  { id: "weighted-pull-up", name: "Weighted Pull-Up", weights: { lat_l: 0.35, lat_r: 0.35, traps_back_l: 0.08, traps_back_r: 0.08, rhomboid_l: 0.02, rhomboid_r: 0.02, biceps_l: 0.05, biceps_r: 0.05, forearm_l: 0.025, forearm_r: 0.025 } },
  { id: "assisted-pull-up-machine", name: "Assisted Pull-Up Machine", aliases: ["Assisted Pull Up"], weights: { lat_l: 0.32, lat_r: 0.32, traps_back_l: 0.07, traps_back_r: 0.07, rhomboid_l: 0.02, rhomboid_r: 0.02, biceps_l: 0.07, biceps_r: 0.07, forearm_l: 0.02, forearm_r: 0.02 } },
  { id: "assisted-pull-up", name: "Assisted Pull Up", weights: { lat_l: 0.32, lat_r: 0.32, traps_back_l: 0.07, traps_back_r: 0.07, rhomboid_l: 0.02, rhomboid_r: 0.02, biceps_l: 0.07, biceps_r: 0.07, forearm_l: 0.02, forearm_r: 0.02 } },
  { id: "lat-pulldown", name: "Lat Pulldown", weights: { lat_l: 0.38, lat_r: 0.38, traps_back_l: 0.05, traps_back_r: 0.05, lower_traps_l: 0.02, lower_traps_r: 0.02, rhomboid_l: 0.01, rhomboid_r: 0.01, biceps_l: 0.03, biceps_r: 0.03, forearm_l: 0.015, forearm_r: 0.015 } },
  { id: "wide-grip-lat-pulldown", name: "Wide Grip Lat Pulldown", weights: { lat_l: 0.38, lat_r: 0.38, traps_back_l: 0.06, traps_back_r: 0.06, rhomboid_l: 0.02, rhomboid_r: 0.02, biceps_l: 0.03, biceps_r: 0.03, forearm_l: 0.01, forearm_r: 0.01 } },
  { id: "close-grip-lat-pulldown", name: "Close Grip Lat Pulldown", weights: { lat_l: 0.34, lat_r: 0.34, traps_back_l: 0.07, traps_back_r: 0.07, rhomboid_l: 0.02, rhomboid_r: 0.02, biceps_l: 0.05, biceps_r: 0.05, forearm_l: 0.02, forearm_r: 0.02 } },
  { id: "reverse-grip-pulldown", name: "Reverse Grip Pull Down", weights: { lat_l: 0.34, lat_r: 0.34, traps_back_l: 0.06, traps_back_r: 0.06, rhomboid_l: 0.02, rhomboid_r: 0.02, biceps_l: 0.06, biceps_r: 0.06, forearm_l: 0.02, forearm_r: 0.02 } },
  { id: "single-arm-cable-lat-pulldown", name: "Single Arm Cable Lat Pulldown", aliases: ["Single Arm Lat Pulldown"], weights: { lat_l: 0.4, lat_r: 0.4, rhomboid_l: 0.05, rhomboid_r: 0.05, biceps_l: 0.04, biceps_r: 0.04, forearm_l: 0.01, forearm_r: 0.01 } },
  { id: "single-arm-lat-pulldown", name: "Single Arm Lat Pulldown", weights: { lat_l: 0.4, lat_r: 0.4, rhomboid_l: 0.05, rhomboid_r: 0.05, biceps_l: 0.04, biceps_r: 0.04, forearm_l: 0.01, forearm_r: 0.01 } },
  { id: "v-bar-pulldown", name: "V Bar Pulldown", weights: { lat_l: 0.35, lat_r: 0.35, traps_back_l: 0.07, traps_back_r: 0.07, rhomboid_l: 0.02, rhomboid_r: 0.02, biceps_l: 0.05, biceps_r: 0.05, forearm_l: 0.01, forearm_r: 0.01 } },
  { id: "cable-crossover-lat-pulldown", name: "Cable Crossover Lat Pulldown", weights: { lat_l: 0.39, lat_r: 0.39, traps_back_l: 0.05, traps_back_r: 0.05, rhomboid_l: 0.03, rhomboid_r: 0.03, biceps_l: 0.02, biceps_r: 0.02, forearm_l: 0.01, forearm_r: 0.01 } },
  { id: "handle-band-lat-pulldown", name: "Handle Band Lat Pulldown", logMode: "reps_only", weights: { lat_l: 0.36, lat_r: 0.36, traps_back_l: 0.06, traps_back_r: 0.06, rhomboid_l: 0.02, rhomboid_r: 0.02, biceps_l: 0.05, biceps_r: 0.05, forearm_l: 0.01, forearm_r: 0.01 } },
  { id: "lat-pullover-machine", name: "Lat Pullover Machine", weights: { lat_l: 0.42, lat_r: 0.42, traps_back_l: 0.06, traps_back_r: 0.06, triceps: 0.04 } },
  { id: "cable-pullover", name: "Cable Pullover", weights: { lat_l: 0.42, lat_r: 0.42, traps_back_l: 0.06, traps_back_r: 0.06, triceps: 0.04 } },
  { id: "ez-bar-pullover", name: "EZ-Bar Pull Over", weights: { lat_l: 0.39, lat_r: 0.39, triceps: 0.08, upper_chest: 0.07, lower_chest: 0.04, traps_back_l: 0.015, traps_back_r: 0.015 } },
  { id: "ez-bar-pjr-pullover", name: "EZ Bar PJR Pull Over", weights: { lat_l: 0.32, lat_r: 0.32, triceps: 0.22, upper_chest: 0.06, lower_chest: 0.03, traps_back_l: 0.025, traps_back_r: 0.025 } },
  { id: "barbell-row", name: "Bent-Over Barbell Row", aliases: ["Bent Over Barbell Row"], weights: { lat_l: 0.28, lat_r: 0.28, traps_back_l: 0.22, traps_back_r: 0.22, rear_delt_l: 0.05, rear_delt_r: 0.05 } },
  { id: "reverse-grip-barbell-row", name: "Reverse Grip Barbell Bent Over Row", aliases: ["Underhanded Bent Over Row"], weights: { lat_l: 0.27, lat_r: 0.27, traps_back_l: 0.16, traps_back_r: 0.16, rear_delt_l: 0.02, rear_delt_r: 0.02, biceps_l: 0.04, biceps_r: 0.04, forearm_l: 0.01, forearm_r: 0.01 } },
  { id: "smith-bent-over-row", name: "Smith Machine Bent Over Row", weights: { lat_l: 0.28, lat_r: 0.28, traps_back_l: 0.17, traps_back_r: 0.17, rear_delt_l: 0.03, rear_delt_r: 0.03, biceps_l: 0.01, biceps_r: 0.01, forearm_l: 0.01, forearm_r: 0.01 } },
  { id: "trap-bar-bent-over-row", name: "Trap Bar Bent Over Row", weights: { lat_l: 0.26, lat_r: 0.26, traps_back_l: 0.18, traps_back_r: 0.18, rear_delt_l: 0.03, rear_delt_r: 0.03, lower_back_l: 0.02, lower_back_r: 0.02, forearm_l: 0.01, forearm_r: 0.01 } },
  { id: "landmine-row", name: "Landmine Row", weights: { lat_l: 0.32, lat_r: 0.32, traps_back_l: 0.12, traps_back_r: 0.12, rear_delt_l: 0.02, rear_delt_r: 0.02, biceps_l: 0.03, biceps_r: 0.03, forearm_l: 0.01, forearm_r: 0.01 } },
  { id: "shotgun-row", name: "Shotgun Row", weights: { lat_l: 0.31, lat_r: 0.31, traps_back_l: 0.13, traps_back_r: 0.13, rear_delt_l: 0.02, rear_delt_r: 0.02, biceps_l: 0.03, biceps_r: 0.03, forearm_l: 0.01, forearm_r: 0.01 } },
  { id: "kettlebell-row", name: "Kettlebell Row", weights: { lat_l: 0.28, lat_r: 0.28, traps_back_l: 0.16, traps_back_r: 0.16, rear_delt_l: 0.03, rear_delt_r: 0.03, biceps_l: 0.02, biceps_r: 0.02, forearm_l: 0.01, forearm_r: 0.01 } },
  { id: "db-row", name: "Dumbbell Row", aliases: ["Dumbbell Bent Over Row"], weights: { lat_l: 0.28, lat_r: 0.28, traps_back_l: 0.17, traps_back_r: 0.17, rear_delt_l: 0.03, rear_delt_r: 0.03, lower_back_l: 0.02, lower_back_r: 0.02 } },
  { id: "db-bent-over-row", name: "Dumbbell Bent Over Row", weights: { lat_l: 0.28, lat_r: 0.28, traps_back_l: 0.17, traps_back_r: 0.17, rear_delt_l: 0.03, rear_delt_r: 0.03, lower_back_l: 0.02, lower_back_r: 0.02 } },
  { id: "seated-cable-row", name: "Seated Cable Row", aliases: ["Cable Row"], weights: { lat_l: 0.3, lat_r: 0.3, traps_back_l: 0.17, traps_back_r: 0.17, lower_traps_l: 0.03, lower_traps_r: 0.03, rear_delt_l: 0.02, rear_delt_r: 0.02, forearm_l: 0.01, forearm_r: 0.01 } },
  { id: "cable-row", name: "Cable Row", weights: { lat_l: 0.3, lat_r: 0.3, traps_back_l: 0.2, traps_back_r: 0.2, rear_delt_l: 0.02, rear_delt_r: 0.02, forearm_l: 0.01, forearm_r: 0.01 } },
  { id: "chest-supported-machine-row", name: "Chest Supported Machine Row", aliases: ["Machine Row"], weights: { lat_l: 0.3, lat_r: 0.3, traps_back_l: 0.17, traps_back_r: 0.17, rear_delt_l: 0.03, rear_delt_r: 0.03 } },
  { id: "seal-row", name: "Seal Row", aliases: ["Barbell Seal Row", "Dumbbell Seal Row", "Chest Supported Barbell Row"], weights: { lat_l: 0.22, lat_r: 0.22, traps_back_l: 0.12, traps_back_r: 0.12, rhomboid_l: 0.06, rhomboid_r: 0.06, rear_delt_l: 0.05, rear_delt_r: 0.05, biceps_l: 0.035, biceps_r: 0.035, forearm_l: 0.015, forearm_r: 0.015 } },
  { id: "machine-row", name: "Machine Row", weights: { lat_l: 0.3, lat_r: 0.3, traps_back_l: 0.17, traps_back_r: 0.17, rear_delt_l: 0.03, rear_delt_r: 0.03 } },
  { id: "high-low-chest-supported-row", name: "High to Low Chest Supported Machine Row", weights: { lat_l: 0.32, lat_r: 0.32, traps_back_l: 0.12, traps_back_r: 0.12, rear_delt_l: 0.02, rear_delt_r: 0.02, biceps_l: 0.02, biceps_r: 0.02, forearm_l: 0.02, forearm_r: 0.02 } },
  { id: "hammerstrength-high-row", name: "Hammerstrength High Row", weights: { lat_l: 0.31, lat_r: 0.31, traps_back_l: 0.13, traps_back_r: 0.13, rear_delt_l: 0.03, rear_delt_r: 0.03, biceps_l: 0.02, biceps_r: 0.02, forearm_l: 0.01, forearm_r: 0.01 } },
  { id: "hammerstrength-iso-row", name: "Hammerstrength Iso Row", weights: { lat_l: 0.3, lat_r: 0.3, traps_back_l: 0.15, traps_back_r: 0.15, rear_delt_l: 0.03, rear_delt_r: 0.03, biceps_l: 0.02, biceps_r: 0.02, forearm_l: 0.01, forearm_r: 0.01 } },
  { id: "incline-db-row", name: "Incline Dumbbell Row", weights: { lat_l: 0.31, lat_r: 0.31, traps_back_l: 0.14, traps_back_r: 0.14, rear_delt_l: 0.03, rear_delt_r: 0.03, biceps_l: 0.02, biceps_r: 0.02 } },
  { id: "t-bar-row-machine", name: "T-Bar Row Machine", aliases: ["T Bar Row"], weights: { lat_l: 0.28, lat_r: 0.28, traps_back_l: 0.175, traps_back_r: 0.175, rear_delt_l: 0.045, rear_delt_r: 0.045 } },
  { id: "t-bar-row", name: "T Bar Row", weights: { lat_l: 0.28, lat_r: 0.28, traps_back_l: 0.175, traps_back_r: 0.175, rear_delt_l: 0.045, rear_delt_r: 0.045 } },
  { id: "barbell-shrug", name: "Barbell Shrug", aliases: ["Barbell Shrugs", "Standing Barbell Shrug", "Standing Barbell Shrugs"], weights: { traps_back_l: 0.46, traps_back_r: 0.46, forearm_l: 0.04, forearm_r: 0.04 } },
  { id: "kelso-shrug", name: "Kelso Shrug", aliases: ["Kelso Shrugs", "Kellso Shrug", "Kellso Shrugs"], weights: { rhomboid_l: 0.2, rhomboid_r: 0.2, traps_back_l: 0.15, traps_back_r: 0.15, lower_traps_l: 0.1, lower_traps_r: 0.1, rear_delt_l: 0.05, rear_delt_r: 0.05 } },
  { id: "face-pull", name: "Face Pull (Cable)", aliases: ["Face Pull"], weights: { rear_delt_l: 0.32, rear_delt_r: 0.32, traps_back_l: 0.18, traps_back_r: 0.18, lower_traps_l: 0.075, lower_traps_r: 0.075 } },
  { id: "reverse-fly", name: "Rear Delt Dumbbell Fly (Bent-Over)", aliases: ["Reverse Fly", "Dumbbell Bent Over Reverse Fly", "Dumbbell Rear Delt Raise", "Dumbbell Back Fly"], weights: { rear_delt_l: 0.47, rear_delt_r: 0.47, traps_back_l: 0.045, traps_back_r: 0.045 } },
  { id: "db-bent-over-reverse-fly", name: "Dumbbell Bent Over Reverse Fly", weights: { rear_delt_l: 0.46, rear_delt_r: 0.46, traps_back_l: 0.04, traps_back_r: 0.04 } },
  { id: "seated-rear-delt-db-fly", name: "Seated Rear Delt Dumbbell Fly", weights: { rear_delt_l: 0.48, rear_delt_r: 0.48, traps_back_l: 0.02, traps_back_r: 0.02 } },
  { id: "incline-rear-delt-fly", name: "Incline Bench Rear Delt Fly (Chest Supported)", weights: { rear_delt_l: 0.5, rear_delt_r: 0.5 } },
  { id: "reverse-pec-deck", name: "Reverse Pec Deck Machine", aliases: ["Machine Reverse Fly"], weights: { rear_delt_l: 0.48, rear_delt_r: 0.48, traps_back_l: 0.02, traps_back_r: 0.02 } },
  { id: "cable-reverse-fly", name: "Cable Reverse Fly (Dual Cable)", aliases: ["Cable Rear Delt Fly"], weights: { rear_delt_l: 0.46, rear_delt_r: 0.46, traps_back_l: 0.04, traps_back_r: 0.04 } },
  { id: "single-arm-cable-reverse-fly", name: "Single Arm Cable Reverse Fly", weights: { rear_delt_l: 0.44, rear_delt_r: 0.44, traps_back_l: 0.06, traps_back_r: 0.06 } },
  { id: "high-cable-reverse-fly", name: "High Cable Reverse Fly", weights: { rear_delt_l: 0.42, rear_delt_r: 0.42, traps_back_l: 0.09, traps_back_r: 0.09 } },
  { id: "cross-over-cable-rear-delt-fly", name: "Cross-Over Cable Rear Delt Fly", weights: { rear_delt_l: 0.43, rear_delt_r: 0.43, traps_back_l: 0.1, traps_back_r: 0.1 } },
  { id: "loop-band-overhead-pull-apart", name: "Loop Band Overhead Pull Apart", logMode: "reps_only", weights: { rear_delt_l: 0.28, rear_delt_r: 0.28, traps_back_l: 0.1, traps_back_r: 0.1, lower_traps_l: 0.05, lower_traps_r: 0.05, rhomboid_l: 0.05, rhomboid_r: 0.05, forearm_l: 0.02, forearm_r: 0.02 } },
  { id: "rear-delt-barbell-row", name: "Rear Delt Barbell Row (Wide Grip)", weights: { rear_delt_l: 0.3, rear_delt_r: 0.3, traps_back_l: 0.3, traps_back_r: 0.3, lat_l: 0.05, lat_r: 0.05 } },
  { id: "chin-up", name: "Chin Up", weights: { lat_l: 0.3, lat_r: 0.3, traps_back_l: 0.08, traps_back_r: 0.08, biceps_l: 0.09, biceps_r: 0.09, forearm_l: 0.03, forearm_r: 0.03 } },
  { id: "neutral-grip-pull-up", name: "Neutral Grip Pull Up", logMode: "reps_only", weights: { lat_l: 0.34, lat_r: 0.34, traps_back_l: 0.07, traps_back_r: 0.07, rhomboid_l: 0.02, rhomboid_r: 0.02, biceps_l: 0.05, biceps_r: 0.05, forearm_l: 0.02, forearm_r: 0.02 } },
  { id: "v-bar-pull-up", name: "V-Bar Pull Up", logMode: "reps_only", weights: { lat_l: 0.34, lat_r: 0.34, traps_back_l: 0.07, traps_back_r: 0.07, rhomboid_l: 0.02, rhomboid_r: 0.02, biceps_l: 0.05, biceps_r: 0.05, forearm_l: 0.02, forearm_r: 0.02 } },
  { id: "australian-pull-up", name: "Australian Pull Up", logMode: "reps_only", weights: { lat_l: 0.27, lat_r: 0.27, traps_back_l: 0.14, traps_back_r: 0.14, rhomboid_l: 0.06, rhomboid_r: 0.06, biceps_l: 0.02, biceps_r: 0.02, forearm_l: 0.01, forearm_r: 0.01 } },
  { id: "ring-row", name: "Ring Row", logMode: "reps_only", weights: { lat_l: 0.26, lat_r: 0.26, traps_back_l: 0.15, traps_back_r: 0.15, rhomboid_l: 0.07, rhomboid_r: 0.07, biceps_l: 0.02, biceps_r: 0.02, forearm_l: 0.01, forearm_r: 0.01 } },
  { id: "trx-power-pull", name: "TRX Power Pull", logMode: "reps_only", weights: { lat_l: 0.22, lat_r: 0.22, traps_back_l: 0.13, traps_back_r: 0.13, rear_delt_l: 0.08, rear_delt_r: 0.08, rhomboid_l: 0.03, rhomboid_r: 0.03, obliques_l: 0.03, obliques_r: 0.03, forearm_l: 0.01, forearm_r: 0.01 } },
  { id: "loop-band-chin-up", name: "Loop Band Chin Up", logMode: "reps_only", weights: { lat_l: 0.3, lat_r: 0.3, traps_back_l: 0.08, traps_back_r: 0.08, biceps_l: 0.09, biceps_r: 0.09, forearm_l: 0.03, forearm_r: 0.03 } },
  { id: "loop-band-wide-grip-pull-up", name: "Loop Band Wide Grip Pull Up", logMode: "reps_only", weights: { lat_l: 0.36, lat_r: 0.36, traps_back_l: 0.08, traps_back_r: 0.08, rhomboid_l: 0.02, rhomboid_r: 0.02, biceps_l: 0.03, biceps_r: 0.03, forearm_l: 0.01, forearm_r: 0.01 } },
  { id: "loop-band-negative-pull-up", name: "Loop Band Negative Pull Up", logMode: "reps_only", weights: { lat_l: 0.37, lat_r: 0.37, traps_back_l: 0.07, traps_back_r: 0.07, rhomboid_l: 0.02, rhomboid_r: 0.02, biceps_l: 0.03, biceps_r: 0.03, forearm_l: 0.01, forearm_r: 0.01 } },
  { id: "butterfly-pull-up", name: "Butterfly Pull Up", logMode: "reps_only", weights: { lat_l: 0.36, lat_r: 0.36, traps_back_l: 0.08, traps_back_r: 0.08, rhomboid_l: 0.02, rhomboid_r: 0.02, biceps_l: 0.02, biceps_r: 0.02, front_delt_l: 0.01, front_delt_r: 0.01, forearm_l: 0.01, forearm_r: 0.01 } },
  { id: "muscle-up", name: "Muscle Up", logMode: "reps_only", weights: { lat_l: 0.22, lat_r: 0.22, traps_back_l: 0.07, traps_back_r: 0.07, biceps_l: 0.04, biceps_r: 0.04, upper_chest: 0.1, lower_chest: 0.08, front_delt_l: 0.03, front_delt_r: 0.03, triceps: 0.08, forearm_l: 0.01, forearm_r: 0.01 } },
  { id: "hip-thrust", name: "Barbell Hip Thrust", aliases: ["Hip Thrust"], weights: { glutes_l: 0.45, glutes_r: 0.45, hamstrings_l: 0.05, hamstrings_r: 0.05, lower_back_l: 0.025, lower_back_r: 0.025 } },
  { id: "dumbbell-hip-thrust", name: "Dumbbell Hip Thrust", weights: { glutes_l: 0.44, glutes_r: 0.44, hamstrings_l: 0.05, hamstrings_r: 0.05, lower_back_l: 0.01, lower_back_r: 0.01 } },
  { id: "elevated-hip-bridge", name: "Elevated Hip Bridge", weights: { glutes_l: 0.43, glutes_r: 0.43, hamstrings_l: 0.07, hamstrings_r: 0.07 } },
  { id: "single-leg-glute-bridge", name: "Single Leg Glute Bridge", weights: { glutes_l: 0.38, glutes_r: 0.38, hamstrings_l: 0.08, hamstrings_r: 0.08, abs: 0.04, obliques_l: 0.02, obliques_r: 0.02 } },
  { id: "single-leg-kickback", name: "Single Leg Kickback", logMode: "reps_only", weights: { glutes_l: 0.38, glutes_r: 0.38, hamstrings_l: 0.1, hamstrings_r: 0.1, lower_back_l: 0.02, lower_back_r: 0.02 } },
  { id: "cable-hip-extension", name: "Cable Hip Extension", weights: { glutes_l: 0.4, glutes_r: 0.4, hamstrings_l: 0.08, hamstrings_r: 0.08, lower_back_l: 0.02, lower_back_r: 0.02 } },
  { id: "medicine-ball-hip-thrusts", name: "Medicine Ball Hip Thrusts", weights: { glutes_l: 0.41, glutes_r: 0.41, hamstrings_l: 0.06, hamstrings_r: 0.06, lower_back_l: 0.03, lower_back_r: 0.03 } },
  { id: "straight-leg-kickback", name: "Straight Leg Kickback", logMode: "reps_only", weights: { glutes_l: 0.34, glutes_r: 0.34, hamstrings_l: 0.12, hamstrings_r: 0.12, lower_back_l: 0.04, lower_back_r: 0.04 } },
  { id: "side-leg-kick", name: "Side Leg Kick", logMode: "reps_only", weights: { glutes_l: 0.42, glutes_r: 0.42, obliques_l: 0.04, obliques_r: 0.04, hamstrings_l: 0.04, hamstrings_r: 0.04 } },
  { id: "glute-kickback-machine", name: "Glute Kickback Machine", weights: { glutes_l: 0.4, glutes_r: 0.4, hamstrings_l: 0.08, hamstrings_r: 0.08, lower_back_l: 0.02, lower_back_r: 0.02 } },
  { id: "loop-band-glute-kickback", name: "Loop Band Glute Kickback", logMode: "reps_only", weights: { glutes_l: 0.39, glutes_r: 0.39, hamstrings_l: 0.09, hamstrings_r: 0.09, lower_back_l: 0.02, lower_back_r: 0.02 } },
  { id: "loop-band-side-step", name: "Loop Band Side Step", logMode: "reps_only", weights: { glutes_l: 0.41, glutes_r: 0.41, obliques_l: 0.04, obliques_r: 0.04, quads_l: 0.05, quads_r: 0.05 } },
  { id: "cable-pull-through", name: "Cable Pull Through", weights: { glutes_l: 0.36, glutes_r: 0.36, hamstrings_l: 0.1, hamstrings_r: 0.1, lower_back_l: 0.04, lower_back_r: 0.04 } },
  { id: "single-leg-cable-kickback", name: "Single Leg Cable Kickback", weights: { glutes_l: 0.41, glutes_r: 0.41, hamstrings_l: 0.08, hamstrings_r: 0.08, lower_back_l: 0.01, lower_back_r: 0.01 } },
  { id: "smith-machine-glute-bridge", name: "Smith Machine Glute Bridge", weights: { glutes_l: 0.44, glutes_r: 0.44, hamstrings_l: 0.05, hamstrings_r: 0.05, lower_back_l: 0.01, lower_back_r: 0.01 } },
  { id: "kneeling-squat", name: "Kneeling Squat", weights: { glutes_l: 0.24, glutes_r: 0.24, hamstrings_l: 0.1, hamstrings_r: 0.1, quads_l: 0.08, quads_r: 0.08, lower_back_l: 0.04, lower_back_r: 0.04, abs: 0.04, obliques_l: 0.02, obliques_r: 0.02 } },
  { id: "prone-flutter-kicks", name: "Prone Flutter Kicks", logMode: "reps_only", weights: { glutes_l: 0.18, glutes_r: 0.18, hamstrings_l: 0.14, hamstrings_r: 0.14, lower_back_l: 0.08, lower_back_r: 0.08, abs: 0.08, obliques_l: 0.06, obliques_r: 0.06 } },
  { id: "hip-abduction-machine", name: "Hip Abduction Machine", weights: { glutes_l: 0.45, glutes_r: 0.45, hamstrings_l: 0.05, hamstrings_r: 0.05 } },
  { id: "hip-adduction-machine", name: "Hip Adduction Machine", weights: { quads_l: 0.35, quads_r: 0.35, hamstrings_l: 0.12, hamstrings_r: 0.12, glutes_l: 0.03, glutes_r: 0.03 } },
  // Conventional deadlift stays on the legacy id so existing PRs/badges/logs keep resolving.
  { id: "barbell-deadlift", name: "Conventional Deadlift", aliases: ["Barbell Deadlift", "Deadlift", "Conventional Barbell Deadlift"], weights: { hamstrings_l: 0.16, hamstrings_r: 0.16, glutes_l: 0.14, glutes_r: 0.14, lower_back_l: 0.12, lower_back_r: 0.12, quads_l: 0.08, quads_r: 0.08 } },
  { id: "romanian-deadlift", name: "Romanian Deadlift", weights: { hamstrings_l: 0.35, hamstrings_r: 0.35, glutes_l: 0.15, glutes_r: 0.15, lower_back_l: 0.075, lower_back_r: 0.075 } },
  { id: "sumo-deadlift", name: "Sumo Deadlift", weights: { hamstrings_l: 0.22, hamstrings_r: 0.22, quads_l: 0.12, quads_r: 0.12, glutes_l: 0.11, glutes_r: 0.11, lower_back_l: 0.05, lower_back_r: 0.05 } },
  { id: "back-extension", name: "Back Extension", weights: { lower_back_l: 0.45, lower_back_r: 0.45, glutes_l: 0.05, glutes_r: 0.05, hamstrings_l: 0.05, hamstrings_r: 0.05 } },
  { id: "lying-leg-curl-machine", name: "Lying Leg Curl Machine", weights: { hamstrings_l: 0.35, hamstrings_r: 0.35, calves_l: 0.08, calves_r: 0.08, glutes_l: 0.07, glutes_r: 0.07 } },
  { id: "seated-leg-curl-machine", name: "Seated Leg Curl Machine", weights: { hamstrings_l: 0.38, hamstrings_r: 0.38, glutes_l: 0.08, glutes_r: 0.08, calves_l: 0.04, calves_r: 0.04 } },
  { id: "hamstring-curl", name: "Hamstring Curl", weights: { hamstrings_l: 0.5, hamstrings_r: 0.5 } },
  { id: "glute-bridge", name: "Glute Bridge", weights: { glutes_l: 0.5, glutes_r: 0.5, hamstrings_l: 0.1, hamstrings_r: 0.1 } },
] as Exercise[];

export const REPS_OPTIONS = Array.from({ length: 50 }, (_, i) => i + 1);
export const WEIGHT_OPTIONS = Array.from({ length: 301 }, (_, i) => i);

export const NICE_NAME: Record<string, string> = {
  upper_chest: "Upper Chest",
  lower_chest: "Lower Chest",
  front_delt_l: "Front Delt (L)",
  front_delt_r: "Front Delt (R)",
  side_delt_l: "Side Delt (L)",
  side_delt_r: "Side Delt (R)",
  traps_front: "Traps (Front)",
  triceps: "Triceps",
  biceps_l: "Biceps (L)",
  biceps_r: "Biceps (R)",
  forearm_l: "Forearm (L)",
  forearm_r: "Forearm (R)",
  abs: "Abs",
  obliques_l: "Obliques (L)",
  obliques_r: "Obliques (R)",
  quads_l: "Quads (L)",
  quads_r: "Quads (R)",
  calves_l: "Calves (L)",
  calves_r: "Calves (R)",
  rear_delt_l: "Rear Delt (L)",
  rear_delt_r: "Rear Delt (R)",
  traps_back_l: "Upper Traps (L)",
  traps_back_r: "Upper Traps (R)",
  traps_back: "Upper Traps",
  lower_traps_l: "Lower Traps (L)",
  lower_traps_r: "Lower Traps (R)",
  lower_traps: "Lower Traps",
  lat_l: "Lat (L)",
  lat_r: "Lat (R)",
  lat: "Latissimus Dorsi",
  rhomboid_l: "Rhomboids (L)",
  rhomboid_r: "Rhomboids (R)",
  rhomboid: "Rhomboids",
  rhomboids: "Rhomboids",
  glutes_l: "Glutes (L)",
  glutes_r: "Glutes (R)",
  glutes: "Glutes",
  hamstrings_l: "Hamstrings (L)",
  hamstrings_r: "Hamstrings (R)",
  hamstrings: "Hamstrings",
  lower_back_l: "Lower Back (L)",
  lower_back_r: "Lower Back (R)",
  lower_back: "Lower Back",
  rear_delt: "Rear Delts",
  triceps_l: "Triceps (L)",
  triceps_r: "Triceps (R)",
};

const normalizeExerciseName = (value: string) => value.trim().toLowerCase();

const exerciseNameVariants = (exercise: Exercise) => [exercise.name, ...(exercise.aliases ?? [])];

export const matchesExerciseName = (exercise: Exercise, candidate: string) => {
  if (!candidate) return false;
  const term = normalizeExerciseName(candidate);
  if (!term) return false;
  return exerciseNameVariants(exercise).some((label) => normalizeExerciseName(label) === term);
};

export const findExerciseByName = (candidate: string) => {
  if (!candidate) return undefined;
  const term = normalizeExerciseName(candidate);
  if (!term) return undefined;
  return EXERCISE_DB.find((exercise) => matchesExerciseName(exercise, term));
};

// Broad search groups are app-only: the Supabase featured_exercises catalog uses concrete muscle ids.
export const FEATURED_SEARCH_EXERCISES_BY_MUSCLE: Record<string, string[]> = {
  chest: [
    "bench-press",
    "db-bench-press",
    "incline-db-press",
    "incline-barbell-bench-press",
    "machine-chest-press",
    "pec-deck",
    "smith-incline-bench-press",
    "dips",
    "cable-fly-high",
    "push-up",
  ],
  shoulders: [
    "ohp",
    "lateral-raise",
    "seated-dumbbell-press",
    "machine-shoulder-press",
    "seated-arnold-press",
    "cable-lateral-raise",
    "reverse-pec-deck",
    "face-pull",
    "front-raise",
    "upright-row",
  ],
  back: [
    "lat-pulldown",
    "pull-up",
    "seated-cable-row",
    "barbell-row",
    "barbell-shrug",
    "chest-supported-machine-row",
    "t-bar-row",
    "db-row",
    "machine-row",
    "face-pull",
  ],
  arms: [
    "bb-curl",
    "triceps-pushdown",
    "db-curl",
    "rope-triceps-pushdown",
    "ez-bar-curl",
    "close-grip-bench-press",
    "db-hammer-curl",
    "ez-skull-crusher",
    "cable-curl",
    "overhead-triceps",
  ],
  legs: [
    "squat",
    "leg-press",
    "romanian-deadlift",
    "leg-extension",
    "hamstring-curl",
    "hip-thrust",
    "bulgarian-split-squat",
    "front-squat",
    "calf-raise",
    "sumo-deadlift",
  ],
};

export const FEATURED_EXERCISES_BY_MUSCLE: Record<string, string[]> = {
  upper_chest: [
    "incline-barbell-bench-press",
    "incline-db-press",
    "smith-incline-bench-press",
    "machine-incline-chest-press",
    "bench-press",
    "db-bench-press",
    "cable-fly-low",
    "dumbbell-incline-fly",
    "incline-dumbbell-squeeze-press",
    "pec-deck",
  ],
  lower_chest: [
    "bench-press",
    "db-bench-press",
    "dips",
    "machine-chest-press",
    "cable-fly-high",
    "decline-bb-press",
    "push-up",
    "pec-deck",
    "smith-bench-press",
    "machine-decline-chest-press",
  ],
  front_delt: [
    "ohp",
    "seated-barbell-shoulder-press",
    "seated-dumbbell-press",
    "standing-dumbbell-shoulder-press",
    "seated-arnold-press",
    "smith-machine-shoulder-press",
    "machine-shoulder-press",
    "push-press",
    "landmine-press",
    "front-raise",
  ],
  side_delt: [
    "lateral-raise",
    "cable-lateral-raise",
    "lateral-raise-machine",
    "seated-lateral-raise",
    "leaning-lateral-raise",
    "behind-back-cable-lateral-raise",
    "upright-row",
    "cable-upright-row",
    "ez-bar-upright-row",
    "wide-grip-upright-row",
  ],
  rear_delt: [
    "reverse-pec-deck",
    "reverse-fly",
    "incline-rear-delt-fly",
    "cable-reverse-fly",
    "seated-rear-delt-db-fly",
    "db-bent-over-reverse-fly",
    "single-arm-cable-reverse-fly",
    "high-cable-reverse-fly",
    "cross-over-cable-rear-delt-fly",
    "face-pull",
  ],
  traps_front: [
    "upright-row",
    "cable-upright-row",
    "ez-bar-upright-row",
    "wide-grip-upright-row",
    "ohp",
    "push-press",
    "standing-military-press",
    "seated-barbell-shoulder-press",
    "farmers-walk",
    "battle-ropes",
  ],
  triceps: [
    "triceps-pushdown",
    "rope-triceps-pushdown",
    "close-grip-bench-press",
    "dips",
    "ez-skull-crusher",
    "bb-skull-crusher",
    "overhead-triceps",
    "overhead-cable-triceps-extension",
    "triceps-extension-machine",
    "reverse-grip-cable-pushdown",
  ],
  biceps: [
    "bb-curl",
    "db-curl",
    "ez-bar-curl",
    "alt-db-curl",
    "db-hammer-curl",
    "cable-curl",
    "preacher-bb-curl",
    "incline-db-curl",
    "concentration-curl",
    "machine-bicep-curl",
  ],
  abs: [
    "crunch",
    "sit-up",
    "plank",
    "leg-raise",
    "hanging-knee-raise",
    "cable-crunch",
    "ab-roller",
    "russian-twist",
    "side-plank",
    "seated-ab-crunch-machine",
  ],
  obliques: [
    "side-plank",
    "russian-twist",
    "cable-woodchopper-high",
    "cable-woodchopper-low",
    "plank",
    "hanging-knee-raise",
    "leg-raise",
    "cable-crunch",
    "standing-cable-crunch",
    "ab-roller",
  ],
  forearm: [
    "farmers-walk",
    "palms-down-barbell-wrist-curl",
    "palms-down-dumbbell-wrist-curl",
    "cable-wrist-curl",
    "plate-pinch",
    "db-hammer-curl",
    "reverse-grip-barbell-curl",
    "db-reverse-curl",
    "cross-body-hammer-curl",
    "reverse-grip-cable-curl",
  ],
  quads: [
    "squat",
    "leg-press",
    "front-squat",
    "hack-squat-machine",
    "leg-extension",
    "smith-squat",
    "goblet-squat",
    "bulgarian-split-squat",
    "db-lunge",
    "belt-squat",
  ],
  calves: [
    "calf-raise",
    "seated-calf-raise",
    "standing-dumbbell-calf-raise",
    "standing-barbell-calf-raise",
    "leg-press-calf-raise",
    "smith-machine-calf-raise",
    "seated-dumbbell-calf-raise",
    "leg-press",
    "squat",
    "bodyweight-squat",
  ],
  glutes: [
    "hip-thrust",
    "glute-bridge",
    "romanian-deadlift",
    "step-up",
    "bulgarian-split-squat",
    "sumo-deadlift",
    "glute-kickback-machine",
    "dumbbell-hip-thrust",
    "hip-abduction-machine",
    "cable-pull-through",
  ],
  hamstrings: [
    "romanian-deadlift",
    "hamstring-curl",
    "lying-leg-curl-machine",
    "seated-leg-curl-machine",
    "barbell-deadlift",
    "sumo-deadlift",
    "glute-bridge",
    "hip-thrust",
    "cable-pull-through",
    "back-extension",
  ],
  lat: [
    "lat-pulldown",
    "pull-up",
    "wide-grip-lat-pulldown",
    "close-grip-lat-pulldown",
    "v-bar-pulldown",
    "reverse-grip-pulldown",
    "seated-cable-row",
    "barbell-row",
    "cable-pullover",
    "lat-pullover-machine",
  ],
  traps_back: [
    "barbell-shrug",
    "barbell-row",
    "seated-cable-row",
    "t-bar-row",
    "machine-row",
    "face-pull",
    "chest-supported-machine-row",
    "landmine-row",
    "hammerstrength-high-row",
    "kelso-shrug",
  ],
  lower_traps: [
    "kelso-shrug",
    "face-pull",
    "loop-band-overhead-pull-apart",
    "pull-up",
    "lat-pulldown",
    "seated-cable-row",
  ],
  rhomboid: [
    "kelso-shrug",
    "ring-row",
    "australian-pull-up",
    "loop-band-overhead-pull-apart",
    "rear-delt-row",
    "trx-power-pull",
    "single-arm-cable-lat-pulldown",
    "single-arm-lat-pulldown",
    "cable-crossover-lat-pulldown",
    "pull-up",
  ],
  lower_back: [
    "barbell-deadlift",
    "romanian-deadlift",
    "sumo-deadlift",
    "back-extension",
    "farmers-walk",
    "cable-pull-through",
    "kettlebell-turkish-get-up",
    "db-row",
    "trap-bar-bent-over-row",
    "hip-thrust",
  ],
};

const FEATURED_MUSCLE_ALIASES: Record<string, string> = {
  chest: "chest",
  pec: "chest",
  pecs: "chest",
  borst: "chest",
  borstspier: "chest",
  borstspieren: "chest",
  shoulder: "shoulders",
  shoulders: "shoulders",
  schouder: "shoulders",
  schouders: "shoulders",
  delt: "shoulders",
  delts: "shoulders",
  deltoid: "shoulders",
  deltoids: "shoulders",
  back: "back",
  rug: "back",
  arm: "arms",
  arms: "arms",
  armen: "arms",
  leg: "legs",
  legs: "legs",
  been: "legs",
  benen: "legs",
  abs: "abs",
  ab: "abs",
  abdominal: "abs",
  abdominals: "abs",
  buik: "abs",
  buikspier: "abs",
  buikspieren: "abs",
  core: "abs",
  oblique: "abs",
  obliques: "abs",
  "schuine buikspieren": "abs",
  obliques_l: "abs",
  obliques_r: "abs",
  bicep: "biceps",
  biceps: "biceps",
  tricep: "triceps",
  triceps: "triceps",
  forearm: "forearm",
  forearms: "forearm",
  onderarm: "forearm",
  onderarmen: "forearm",
  forearm_l: "forearm",
  forearm_r: "forearm",
  quad: "quads",
  quads: "quads",
  quadricep: "quads",
  quadriceps: "quads",
  glute: "glutes",
  glutes: "glutes",
  bil: "glutes",
  billen: "glutes",
  glutes_l: "glutes",
  glutes_r: "glutes",
  hamstring: "hamstrings",
  hamstrings: "hamstrings",
  hamstrings_l: "hamstrings",
  hamstrings_r: "hamstrings",
  calf: "calves",
  calves: "calves",
  kuit: "calves",
  kuiten: "calves",
  lat: "lat",
  lats: "lat",
  lower_traps: "lower_traps",
  "lower traps": "lower_traps",
  "lower trap": "lower_traps",
  rhomboids: "rhomboid",
  trap: "traps_back",
  traps: "traps_back",
  trapezius: "traps_back",
  "lower back": "lower_back",
};

export const featuredMuscleKeyFor = (muscle: string | null | undefined) => {
  if (!muscle) return undefined;
  const normalized = muscle.trim().toLowerCase().replace(/_stroke$/, "");
  if (!normalized) return undefined;
  if (FEATURED_SEARCH_EXERCISES_BY_MUSCLE[normalized]) return normalized;
  if (FEATURED_EXERCISES_BY_MUSCLE[normalized]) return normalized;
  const underscored = normalized.replace(/[\s-]+/g, "_");
  if (FEATURED_SEARCH_EXERCISES_BY_MUSCLE[underscored]) return underscored;
  if (FEATURED_EXERCISES_BY_MUSCLE[underscored]) return underscored;
  const base = underscored.replace(/_(l|r)$/, "");
  return (
    FEATURED_MUSCLE_ALIASES[normalized] ??
    FEATURED_MUSCLE_ALIASES[underscored] ??
    FEATURED_MUSCLE_ALIASES[base] ??
    base
  );
};

export const featuredExerciseIdsForMuscle = (muscle: string | null | undefined) => {
  const key = featuredMuscleKeyFor(muscle);
  return key
    ? (
        FEATURED_SEARCH_EXERCISES_BY_MUSCLE[key] ??
        FEATURED_EXERCISES_BY_MUSCLE[key] ??
        []
      ).slice(0, 10)
    : [];
};
